name = "SthenoCompat"
uuid = "546e0efb-fb2c-448f-84b1-492c8da47da7"
authors = ["yiyuezhuo <yiyuezhuo@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Stheno = "8188c328-b5d6-583d-959b-9690869a5511"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Zygote = "0.5"
Stheno = "0.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
